#!/usr/bin/env bash
# Installs nginx server

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
sed -i 's/# listen 80;/listen 80;/' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
service nginx restart
